
package com.foodpanda;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DiscountCalculatorService", targetNamespace = "http://foodpanda.com/", wsdlLocation = "http://192.168.0.240:1000/FoodPanda/DiscountCalculator?wsdl")
public class DiscountCalculatorService
    extends Service
{

    private final static URL DISCOUNTCALCULATORSERVICE_WSDL_LOCATION;
    private final static WebServiceException DISCOUNTCALCULATORSERVICE_EXCEPTION;
    private final static QName DISCOUNTCALCULATORSERVICE_QNAME = new QName("http://foodpanda.com/", "DiscountCalculatorService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.0.240:1000/FoodPanda/DiscountCalculator?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DISCOUNTCALCULATORSERVICE_WSDL_LOCATION = url;
        DISCOUNTCALCULATORSERVICE_EXCEPTION = e;
    }

    public DiscountCalculatorService() {
        super(__getWsdlLocation(), DISCOUNTCALCULATORSERVICE_QNAME);
    }

    public DiscountCalculatorService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DISCOUNTCALCULATORSERVICE_QNAME, features);
    }

    public DiscountCalculatorService(URL wsdlLocation) {
        super(wsdlLocation, DISCOUNTCALCULATORSERVICE_QNAME);
    }

    public DiscountCalculatorService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DISCOUNTCALCULATORSERVICE_QNAME, features);
    }

    public DiscountCalculatorService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DiscountCalculatorService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DiscountCalculator
     */
    @WebEndpoint(name = "DiscountCalculatorPort")
    public DiscountCalculator getDiscountCalculatorPort() {
        return super.getPort(new QName("http://foodpanda.com/", "DiscountCalculatorPort"), DiscountCalculator.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DiscountCalculator
     */
    @WebEndpoint(name = "DiscountCalculatorPort")
    public DiscountCalculator getDiscountCalculatorPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://foodpanda.com/", "DiscountCalculatorPort"), DiscountCalculator.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DISCOUNTCALCULATORSERVICE_EXCEPTION!= null) {
            throw DISCOUNTCALCULATORSERVICE_EXCEPTION;
        }
        return DISCOUNTCALCULATORSERVICE_WSDL_LOCATION;
    }

}
