
package com.foodpanda;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DiscountCalculator", targetNamespace = "http://foodpanda.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DiscountCalculator {


    /**
     * 
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "calcDiscount", targetNamespace = "http://foodpanda.com/", className = "com.foodpanda.CalcDiscount")
    @ResponseWrapper(localName = "calcDiscountResponse", targetNamespace = "http://foodpanda.com/", className = "com.foodpanda.CalcDiscountResponse")
    @Action(input = "http://foodpanda.com/DiscountCalculator/calcDiscountRequest", output = "http://foodpanda.com/DiscountCalculator/calcDiscountResponse")
    public double calcDiscount(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0);

}
